<?php

/*!
 * Copyright © 2016 Rainer Rillke <rillke@wikipedia.de>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 * http://www.gnu.org/copyleft/gpl.html
 *
 */
class FormDefinition {

	public static function get() {
		return array(
			'firstname' => array(
				'label' => 'First name*'
			),
			'lastname' => array(
				'label' => 'Last name*'
			),
			'gender' => array(
				'label' => 'How do you prefer to be described?*',
				'radio' => array(
					'female' => array(
						'label' => 'She takes part in HalLeiLujah'
					),
					'male' => array(
						'label' => 'He takes part in HalLeiLujah'
					),
					'neutral' => array(
						'label' => 'They take part in HalLeiLujah'
					)
				),
				'default' => 'neutral'
			),
			'lc' => array(
				'label' => 'Local Committee or International Office in Germany*',
				'placeholder' => 'LC or AAA/ University in Germany',
				'autosuggest' => array(
					'Akad. Auslandsamt FH Erfurt',
					'Akad. Auslandsamt FH Niederrhein',
					'Akad. Auslandsamt FH Osnabrück',
					'Akad. Auslandsamt FH Westküste',
					'Akad. Auslandsamt FH Wismar',
					'Akad. Auslandsamt HS Merseburg',
					'Akad. Auslandsamt HS Zittau',
					'Akad. Auslandsamt HS Zwickau',
					'Akad. Auslandsamt HU Berlin',
					'Akad. Auslandsamt TU Clausthal',
					'Akad. Auslandsamt U Düsseldorf ',
					'Akad. Auslandsamt U Gießen',
					'Akad. Auslandsamt U Greifswald',
					'Akad. Auslandsamt U Kassel',
					'Akad. Auslandsamt U Leipzig',
					'Akad. Auslandsamt U Magdeburg',
					'Akad. Auslandsamt U Siegen',
					'Akad. Auslandsamt U Weimar',
					'Akad. Auslandsamt U Wuppertal',
					'HS Emden-Leer / FB T',
					'HS OWL',
					'IAESTE/AIESEC-LC TU Berlin',
					'IAESTE/AIESEC-LC TU Braunschweig',
					'IAESTE/AIESEC-LC TU Kaiserslautern',
					'IAESTE/AIESEC-LC U Paderborn',
					'IAESTE-LC FH Anhalt',
					'IAESTE-LC FH Harz',
					'IAESTE-LC FH Köln',
					'IAESTE-LC FH Lübeck',
					'IAESTE-LC Hamburg',
					'IAESTE-LC HS München',
					'IAESTE-LC KIT Karlsruhe',
					'IAESTE-LC RWTH Aachen',
					'IAESTE-LC TU Chemnitz',
					'IAESTE-LC TU Cottbus',
					'IAESTE-LC TU Darmstadt',
					'IAESTE-LC TU Dresden',
					'IAESTE-LC TU Freiberg',
					'IAESTE-LC TU Freising-Weihenstephan',
					'IAESTE-LC TU Ilmenau',
					'IAESTE-LC TU München',
					'IAESTE-LC U Bayreuth',
					'IAESTE-LC U Bochum',
					'IAESTE-LC U Bonn',
					'IAESTE-LC U Bremen',
					'IAESTE-LC U Erlangen',
					'IAESTE-LC U Freiburg',
					'IAESTE-LC U Göttingen',
					'IAESTE-LC U Halle',
					'IAESTE-LC U Hannover',
					'IAESTE-LC U Jena',
					'IAESTE-LC U Kiel',
					'IAESTE-LC U Konstanz',
					'IAESTE-LC U Lüneburg',
					'IAESTE-LC U Mainz',
					'IAESTE-LC U Oldenburg',
					'IAESTE-LC U Oldenburg ',
					'IAESTE-LC U Potsdam',
					'IAESTE-LC U Rostock',
					'IAESTE-LC U Saarbrücken',
					'IAESTE-LC U Stuttgart',
					'info later',
					'Info later',
					'Mosaic',
					'Sekretariat Prof. Unger',
					'Tübingen!',
					'without'
				)
			),
			'homecountry' => array(
				'label' => 'Which is your home region?*',
				'placeholder' => 'home region - e.g. Russia',
				'autosuggest' => array(
					'Andorra',
					'United Arab Emirates',
					'Afghanistan',
					'Antigua and Barbuda',
					'Anguilla',
					'Albania',
					'Armenia',
					'Angola',
					'Antarctica',
					'Argentina',
					'American Samoa',
					'Austria',
					'Australia',
					'Aruba',
					'Åland Islands',
					'Azerbaijan',
					'Bosnia and Herzegovina',
					'Barbados',
					'Bangladesh',
					'Belgium',
					'Burkina Faso',
					'Bulgaria',
					'Bahrain',
					'Burundi',
					'Benin',
					'Saint Barthélemy',
					'Bermuda',
					'Brunei Darussalam',
					'Bolivia',
					'Caribbean Netherlands ',
					'Brazil',
					'Bahamas',
					'Bhutan',
					'Bouvet Island',
					'Botswana',
					'Belarus',
					'Belize',
					'Canada',
					'Cocos (Keeling) Islands',
					'Congo',
					'Central African Republic',
					'Congo',
					'Switzerland',
					'Côte d\'Ivoire',
					'Cook Islands',
					'Chile',
					'Cameroon',
					'China',
					'Colombia',
					'Costa Rica',
					'Cuba',
					'Cape Verde',
					'Curaçao',
					'Christmas Island',
					'Cyprus',
					'Czech Republic',
					'Germany',
					'Djibouti',
					'Denmark',
					'Dominica',
					'Dominican Republic',
					'Algeria',
					'Ecuador',
					'Estonia',
					'Egypt',
					'Western Sahara',
					'Eritrea',
					'Spain',
					'Ethiopia',
					'Finland',
					'Fiji',
					'Falkland Islands',
					'Micronesia',
					'Faroe Islands',
					'France',
					'Gabon',
					'United Kingdom',
					'Grenada',
					'Georgia',
					'French Guiana',
					'Guernsey',
					'Ghana',
					'Gibraltar',
					'Greenland',
					'Gambia',
					'Guinea',
					'Guadeloupe',
					'Equatorial Guinea',
					'Greece',
					'South Georgia and the South Sandwich Islands',
					'Guatemala',
					'Guam',
					'Guinea-Bissau',
					'Guyana',
					'Hong Kong',
					'Heard and McDonald Islands',
					'Honduras',
					'Croatia',
					'Haiti',
					'Hungary',
					'Indonesia',
					'Ireland',
					'Israel',
					'Isle of Man',
					'India',
					'British Indian Ocean Territory',
					'Iraq',
					'Iran',
					'Iceland',
					'Italy',
					'Jersey',
					'Jamaica',
					'Jordan',
					'Japan',
					'Kenya',
					'Kyrgyzstan',
					'Cambodia',
					'Kiribati',
					'Comoros',
					'Saint Kitts and Nevis',
					'North Korea',
					'South Korea',
					'Kuwait',
					'Cayman Islands',
					'Kazakhstan',
					'Lao People\'s Democratic Republic',
					'Lebanon',
					'Saint Lucia',
					'Liechtenstein',
					'Sri Lanka',
					'Liberia',
					'Lesotho',
					'Lithuania',
					'Luxembourg',
					'Latvia',
					'Libya',
					'Morocco',
					'Monaco',
					'Moldova',
					'Montenegro',
					'Saint-Martin (France)',
					'Madagascar',
					'Marshall Islands',
					'Macedonia',
					'Mali',
					'Myanmar',
					'Mongolia',
					'Macau',
					'Northern Mariana Islands',
					'Martinique',
					'Mauritania',
					'Montserrat',
					'Malta',
					'Mauritius',
					'Maldives',
					'Malawi',
					'Mexico',
					'Malaysia',
					'Mozambique',
					'Namibia',
					'New Caledonia',
					'Niger',
					'Norfolk Island',
					'Nigeria',
					'Nicaragua',
					'The Netherlands',
					'Norway',
					'Nepal',
					'Nauru',
					'Niue',
					'New Zealand',
					'Oman',
					'Panama',
					'Peru',
					'French Polynesia',
					'Papua New Guinea',
					'Philippines',
					'Pakistan',
					'Poland',
					'St. Pierre and Miquelon',
					'Pitcairn',
					'Puerto Rico',
					'Palestine',
					'Portugal',
					'Palau',
					'Paraguay',
					'Qatar',
					'Réunion',
					'Romania',
					'Serbia',
					'Russian Federation',
					'Rwanda',
					'Saudi Arabia',
					'Solomon Islands',
					'Seychelles',
					'Sudan',
					'Sweden',
					'Singapore',
					'Saint Helena',
					'Slovenia',
					'Svalbard and Jan Mayen Islands',
					'Slovakia',
					'Sierra Leone',
					'San Marino',
					'Senegal',
					'Somalia',
					'Suriname',
					'South Sudan',
					'Sao Tome and Principe',
					'El Salvador',
					'Sint Maarten (Dutch part)',
					'Syria',
					'Swaziland',
					'Turks and Caicos Islands',
					'Chad',
					'French Southern Territories',
					'Togo',
					'Thailand',
					'Tajikistan',
					'Tokelau',
					'Timor-Leste',
					'Turkmenistan',
					'Tunisia',
					'Tonga',
					'Turkey',
					'Trinidad and Tobago',
					'Tuvalu',
					'Taiwan',
					'Tanzania',
					'Ukraine',
					'Uganda',
					'United States Minor Outlying Islands',
					'United States',
					'Uruguay',
					'Uzbekistan',
					'Vatican',
					'Saint Vincent and the Grenadines',
					'Venezuela',
					'Virgin Islands (British)',
					'Virgin Islands (U.S.)',
					'Vietnam',
					'Vanuatu',
					'Wallis and Futuna Islands',
					'Samoa',
					'Yemen',
					'Mayotte',
					'South Africa',
					'Zambia',
					'Zimbabwe'
				)
			),
			'email' => array(
				'label' => 'e-Mail address*',
				'placeholder' => 'somebody@example.com',
				'type' => 'email'
			),
			'mobile' => array(
				'label' => 'Mobile phone number',
				'placeholder' => '+49 150 7890123456',
				'type' => 'tel',
				'required' => false
			),
			'food' => array(
				'label' => 'Which kind of food is problematic for you?',
				'placeholder' => 'type for suggestions ...',
				'autosuggest' => array(
					'pork',
					'beef',
					'all non- kosher (I\'ll care myself for my food)',
					'all non- vegetarian food',
					'all non- vegan food',
					'milk',
					'gluten',
					'fish',
					'meat'
				),
				'required' => false
			),
			'payment' => array(
				'label' => 'Preferred payment option*',
				'radio' => array(
					#'paypal' => array(
					#	'label' => 'PayPal, 5 days in advance'
					#),
					'wiretransfer' => array(
						'label' => 'Wire-transfer, 5 days in advance'
					),
					'cash' => array(
						'label' => 'Cash, on arrival'
					)
				)
			),
			'comment' => array(
				'label' => 'Comment',
				'placeholder' => 'In case you want to organize lodging your own or if there are other important things like the need for special accommodation we should be aware of or if you have questions ... here they go',
				'type' => 'textarea'
			),
			'dataprotection' => array(
				'label' => 'I agree that my data is saved and processed by IAESTE LC Halle. I allow IAESTE LC Halle and IAESTE Team Leipzig to send me e-Mail regarding this event and to use my phone number for contacting me about this event. I have the right to cancel this agreement at any time by sending an e-Mail to IAESTE@uni-halle.de demanding that but in this case I will keep myself prepared for updates regarding this event by regularly visiting the website and e-Mailing IAESTE LC Halle prior to starting travelling to Leipzig. I can cancel my event registration but I might be obliged to pay compensation for expenses the organizers had due to late cancellation on your side. I will only register once. I will care for planning the journey and the fare to Leipzig and from Halle myself. I am at least 18 years old.',
				'type' => 'checkbox'
			)
		);
	}
}
